### PR TITLE
FIX: Move untar to bclconvert and bcl2fastq processes

### PR DESCRIPTION
**Pull request by maxulysse**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/demultiplex _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by matthdsm — APPROVED** [review]
Seems to be okay!

**Comment by matthdsm** [comment]
Would you also be able to built the untar cmd into `bases2fastq`? If I'm not mistaken, we would be able to completely remove the tar module then.

**Comment by maxulysse** [comment]
> 

I'll have a look at it rn, thanks for the idea

**Comment by Emiller88** [comment]
Before we merge this, can we use `nf-core modules patch`?

**Comment by matthdsm** [comment]
> Before we merge this, can we use nf-core modules patch?
Maxime will be updating the modules upstream so we won't need to I think

**Comment by maxulysse** [comment]
cf https://github.com/nf-core/modules/pull/3311

**Comment by maxulysse** [comment]
I'm syncing both PR.
That way I can try my branch, and when we merge https://github.com/nf-core/modules/pull/3311, I can sync the modules here and merge this one.

**Comment by maxulysse** [comment]
Tried it locally on a folder + on a tar.
Tried it on AWS on a tar.
All :heavy_check_mark:

**Comment by matthdsm** [comment]
Merge away then!

**Pull request merged**
