### PR TITLE
Pre-release v1.4.1

### PR DESCRIPTION
**Pull request by Aratz**
Pre-release of v1.4.1. The main motivation for this release is fixing #175 

## PR checklist
- [X] `nf-core bump-version 1.4.1`
- [X] `nf-core lint --release`
- [X] Update  `CHANGELOG.md`

### CODE REVIEW

**Comment by Aratz** [comment]
I suspect the tests fail because of the 2.13 template update :facepalm: Is there a way to circumvent this?

**Comment by nvnieuwk** [comment]
> I suspect the tests fail because of the 2.13 template update 🤦 Is there a way to circumvent this?

Updating to template v2.13? :grin:

**Comment by Aratz** [comment]
Not sure I want to go down that road just now, haven't you seen #nf-core-memes? :see_no_evil: :sweat_smile:

**Comment by Aratz** [comment]
I mean if the idea is to get nf-validation pinned to 1.1.3 as fast as possible then there should be another way, otherwise the release will have to wait a few weeks :grimacing:

**Comment by nvnieuwk** [comment]
Good point, maybe you can temporarily pin the 2.12 version of nf-core tools in the CI workflow YAML and make sure the linting doesn't check the YAML file

**Comment by Aratz** [comment]
Should be all good now, thanks for the suggestion :)

**Review by nvnieuwk — APPROVED** [review]

**Pull request merged**
