### PR TITLE
Updated modules and subworkflows

### PR DESCRIPTION
**Pull request by nschcolnicov**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/demultiplex _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by nschcolnicov** [comment]
@apeltzer There seems to be an issue with the new module from MultiQC, when using the latest containers kraken report does not get added to it. Already reported the issue in MultiQC:
https://github.com/MultiQC/MultiQC/issues/2801

**Comment by nschcolnicov** [comment]
sgdemux and fqtk now sometimes generate an additional task, possibly retrying a failed execution, not sure because I haven't been able to reproduce when running locally

**Comment by apeltzer** [comment]
MQC 1.25 (see PR https://github.com/nf-core/modules/pull/6655#event-14291850822) should fix this

**Comment by apeltzer** [comment]
Merging this into a branch on nf-core already 👍🏻

**Pull request merged**
