### PR TITLE
fix: closure bug when per flow cell manifest is not included

### PR DESCRIPTION
**Pull request by k1sauce**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/demultiplex _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by k1sauce** [comment]
Hmm, I am not sure why the bases2fastq RunManifest.json hash changes, see https://github.com/nf-core/demultiplex/pull/186/commits/41eba2392415eab6d2e67a57d3eb164dbbb5e9db

This PR fixes a bug introduced by #186

**Comment by Aratz** [comment]
Hmm, this specific snapshot looks unstable, otherwise PR looks good, just quickly looking into this before I approve.

**Review by Aratz — COMMENTED** [review]
I found it, in `RunManifest.json`, the lane order is random and may change between runs. This is a diff between files with checksum `d4ecdb19e5fbcffab3e6e770c34023fb` and `f18eddb73c7051db0ef5c44e6eced9ec`:
```
18c18
<             "Lane": 1,
---
>             "Lane": 2,
381c381
<             "Lane": 2,
---
>             "Lane": 1,
```

I think it's better to exclude this file from the snapshot for now.

**Review by maxulysse — APPROVED** [review]
Could you update CHANGELOG?

**Review by maxulysse — APPROVED** [review]

**Pull request merged**
