### PR TITLE
Rewrite + add bcl-convert

### PR DESCRIPTION
**Pull request by matthdsm**
Attempt at reviving the workflow, add bcl-convert, drop complexities, drop qc
Doesn't work yet!

Related to https://github.com/nf-core/modules/issues/1515
Test data at https://github.com/nf-core/test-datasets/tree/demultiplex

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [x] If you've fixed a bug or added code that should be tested, add tests!
 - [x] If necessary, also make a PR on the [nf-core/demultiplex branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/demultiplex)
 - [x] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [x] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by matthdsm** [comment]
We're getting there, but there's still something going on with the software version dump `CUSTOM_DUMPSOFTWAREVERSIONS`

**Comment by matthdsm** [comment]
Before merging this into dev, I'd look into fixing and merging https://github.com/nf-core/modules/pull/1569 so we can remove bclconvert from the local modules

**Comment by Emiller88** [comment]
I'm fine with whatever you want to do. See #37, I usually like to dogfood the modules/subworkflows in a pipeline and then upstream the fixes. 

We should also be able to test `bclconvert` in nf-core modules now though with that test dataset you made... :rocket:

**Comment by matthdsm** [comment]
@Emiller88, do you think we need to attach meta to all the `bclconvert` outputs or just the fastq?

**Comment by matthdsm** [comment]
@Emiller88,  good enough for dev?

**Pull request merged**
