### PR TITLE
Update to latest bcl_demultiplex sub workflow

### PR DESCRIPTION
**Pull request by k1sauce**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/demultiplex _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by maxulysse** [comment]
Can you add an entry for this PR in CHANGELOG?

**Review by nschcolnicov — APPROVED** [review]
Nice job!

**Review by apeltzer — APPROVED** [review]

**Comment by apeltzer** [comment]
Do you want to work on this @k1sauce by adding the point above to changelog and resolving the two small merge conflicts ? If not, let us know and we can take it from there prior to releasing a new 1.5.0 release 👍🏻

**Comment by k1sauce** [comment]
Please takeover I have been unable to work on it recently

**Comment by apeltzer** [comment]
@atrigila  / @nschcolnicov can you push this past the finish line please :) Thank you :)

**Comment by apeltzer** [comment]
Thanks @k1sauce - merged it and will be part of 1.5.0 :)

**Comment by k1sauce** [comment]
Thanks everyone!

**Pull request merged**
