### PR TITLE
Update diagram

### LINKED ISSUE #261: Update figure
### Description of feature

Missing mkfastq at the moment

### PR DESCRIPTION
**Pull request by atrigila**
Closes #261 

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/demultiplex _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by grst** [comment]
What about cellranger? Wouldn't that be a completely separate demultiplexing route?

**Comment by apeltzer** [comment]
It's hard to see but mkfastq is the cell ranger part no? Although I think that's not compatible with samshee I am afraid ...

**Comment by grst** [comment]
ah, got it. Not sure about samshee... it should still use an illumina samplesheet, no?

**Comment by atrigila** [comment]
In the code we run `samshee` in three demultiplexers:
https://github.com/nf-core/demultiplex/blob/17cde5d8f22f5327beac9637e941e4775ada1b3f/workflows/demultiplex.nf#L96
I used that as reference.

**Comment by apeltzer** [comment]
Then all fine 😉😎

**Pull request merged**
