### PR TITLE
FEAT: update bclconvert to 4.2.4

### LINKED ISSUE #150: [Question]: Upgrading bcl-convert to 4.2.4
Hi @robsyme and @Emiller88 

I find that nf-core/demultiplex uses bcl-convert:4.0.3 - https://github.com/nf-core/modules/blob/master/modules/nf-core/bclconvert/main.nf#L5

Illumina has made lots of changes to bcl-convert 4.1.5 and in 4.2.4 (current version) 
- screenshot below from https://support.illumina.com/content/dam/illumina-support/documents/downloads/software/BCLConvert/v4/200040848_00_4.2.4_BCLConvert_Customer_Release_Notes.pdf

I think the pipeline should be updated to use 4.2.4 
- https://support.illumina.com/sequencing/sequencing_software/bcl-convert/downloads.html

image

Thoughts?

### PR DESCRIPTION
**Pull request by maxulysse**
close #150

### CODE REVIEW

**Comment by maxulysse** [comment]
replace #151

**Review by Emiller88 — CHANGES_REQUESTED** [review]
LGTM, snapshots need to be bumped though, and the CHANGELOG updated!

I'll do it later if no one get's around to it.

**Comment by maxulysse** [comment]
> LGTM, snapshots need to be bumped though, and the CHANGELOG updated!
> 
> I'll do it later if no one get's around to it.

I had the snapshot, but forgot to commit and push...
:facepalm:

**Review by Emiller88 — APPROVED** [review]
Thanks! I think we need a GitHub bot to show the diff and ask if you want to update the snapshot 🤔 

It shouldn't happen automatically that defeats the purpose of a snapshot 
image

**Comment by pilare** [comment]
Are there chances for a release soon with that would include latest BCL Convert? We are actively using that nfcore/demultiplex pipeline in our solution but for reproducibility reasons we do not want to use dev branch builds of the pipeline.  I do see that there are 2 tasks left in 1.4.0 milestones, but one seems to be solved on other PR and the other needs some fixes in the tests. Thanks for that effort we do see a lot of value in this pipeline for the community, we would like to contribute more, but also laking bandwidth to do so :/

**Pull request merged**
