### PR TITLE
Update docker file for cellranger

### PR DESCRIPTION
**Pull request by TomKellyGenetics**
Cellranger requires a specific implementation of tSNE. See PR #5 and #7 for related changes.

Many thanks to contributing to nf-core/demultiplex!

Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).

## PR checklist
 - [x] This comment contains a description of changes (with reason)
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] If necessary, also make a PR on the [nf-core/demultiplex branch on the nf-core/test-datasets repo]( https://github.com/nf-core/test-datasets/pull/new/nf-core/demultiplex)
 - [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
 - [ ] Make sure your code lints (`nf-core lint .`).
 - [ ] Documentation in `docs` is updated
 - [ ] `CHANGELOG.md` is updated
 - [ ] `README.md` is updated

**Learn more about contributing:** https://github.com/nf-core/demultiplex/tree/master/.github/CONTRIBUTING.md

### CODE REVIEW

**Comment by TomKellyGenetics** [comment]
I consider this repository stable now. It runs the test job locally. All that's left is configuring GitHub Integrations (autobuild and autotest). https://github.com/TomKellyGenetics/cellranger_clean/

**Comment by drpatelh** [comment]
Thanks for voluntarily coming in to suggest these changes @TomKellyGenetics 😎 . We should get an automated build on Dockerhub once this PR is merged. Once the container has build successfully I will most likely switch off the autobuilds due to these crazy dependency issues. I think it will be fine to have a static version of the container for now as long as its working!

**Comment by drpatelh** [comment]
Build is still failing because Dockerhub cant find `requirements.txt`:

```
---> b52b89f29318
Step 12/31 : COPY requirements.txt /opt/requirements.txt
COPY failed: stat /var/lib/docker/tmp/docker-builder130847410/requirements.txt: no such file or directory
```

**Comment by drpatelh** [comment]
I realised its probably much easier to just get the Docker image you have kindly provided on Dockerhub @TomKellyGenetics . Hope thats ok?
https://github.com/nf-core/demultiplex/pull/10/commits/d16ce509433caaa1d63dbd809bc0bd4c160bdf2d

**Comment by TomKellyGenetics** [comment]
I think this is because it requires a "requirements.txt" in the working directory when `docker build` is running. For example this one https://github.com/TomKellyGenetics/cellranger_clean/blob/master/requirements.txt

> Build is still failing because Dockerhub cant find `requirements.txt`:
> 
> ```
> ---> b52b89f29318
> Step 12/31 : COPY requirements.txt /opt/requirements.txt
> COPY failed: stat /var/lib/docker/tmp/docker-builder130847410/requirements.txt: no such file or directory
> ```

I'm okay with this and intend to leave it stable for my purposes (a lot of dependencies are current versions or specific commits to avoid updates breaking it). Credit should go to the original developers of cellranger for releasing it open-source and to @mckinsel for building a docker image of an older version: https://github.com/mckinsel/cellranger_clean

> I realised its probably much easier to just get the Docker image you have kindly provided on Dockerhub @TomKellyGenetics . Hope thats ok?
> [d16ce50](https://github.com/nf-core/demultiplex/commit/d16ce509433caaa1d63dbd809bc0bd4c160bdf2d)

**Pull request merged**
